# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-11-10 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20181110_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='title',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140),
        ),
    ]
